import {
  IconAlertTriangle,
  IconArrowBackUp,
  IconArrowsShuffle,
  IconBook2,
  IconBooks,
  IconChevronRight,
  IconClock,
  IconCloudUpload,
  IconDatabase,
  IconFilePencil,
  IconHexagon,
  IconHistory,
  IconInfoCircle,
  IconLanguage,
  IconLayoutDashboard,
  IconNumber1,
  IconNumber2,
  IconNumber3,
  IconNumber4,
  IconNumber5,
  IconNumber6,
  IconPalette,
  IconRefresh,
  IconRobot,
  IconSearch,
  IconSettings,
  IconSpeakerphone,
  IconUserCircle,
  IconUsers,
} from '@tabler/icons-react-native';
import type { ComponentProps, ComponentType } from 'react';

import type { NativeIconName } from '@/components/native-icon-types';

export type TablerNativeIcon = ComponentType<ComponentProps<typeof IconUserCircle>>;

export const tablerNativeIcons: Record<NativeIconName, TablerNativeIcon> = {
  account: IconUserCircle,
  announcement: IconSpeakerphone,
  appearance: IconPalette,
  badgeAi: IconRobot,
  badgeEdit: IconFilePencil,
  badgeFilter1: IconNumber1,
  badgeFilter2: IconNumber2,
  badgeFilter3: IconNumber3,
  badgeFilter4: IconNumber4,
  badgeFilter5: IconNumber5,
  badgeFilter6: IconNumber6,
  badgeHistory: IconHistory,
  badgeJapanese: IconBook2,
  badgeLevel: IconHexagon,
  badgeReply: IconArrowBackUp,
  badgeTranslate: IconLanguage,
  books: IconBooks,
  cache: IconDatabase,
  chevronRight: IconChevronRight,
  clock: IconClock,
  cloudSync: IconCloudUpload,
  community: IconUsers,
  content: IconLayoutDashboard,
  discover: IconBook2,
  error: IconAlertTriangle,
  info: IconInfoCircle,
  progress: IconRefresh,
  reader: IconBook2,
  search: IconSearch,
  settings: IconSettings,
  sync: IconArrowsShuffle,
};
