// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode83`, `decode_ac`, `decode_dc`, `linear_to_srgb`, `sign_pow`, `srgb_to_linear`

/// 将 BlurHash 字符串解码为 `width x height` 的 RGBA8888 像素（每像素 4 字节，alpha=255）。
///
/// FRB 会把返回的 `Vec<u8>` 拷入 Dart `Uint8List`；Dart 侧再交给
/// `ui.decodeImageFromPixels` 生成 `ui.Image`。
Future<Uint8List> blurHashDecodeRgba({
  required String blurHash,
  required int width,
  required int height,
  required double punch,
}) => RustLib.instance.api.crateApiBlurhashBlurHashDecodeRgba(
  blurHash: blurHash,
  width: width,
  height: height,
  punch: punch,
);
